spring:
  application:
    name: mcp-sparql-server
  ai:
    mcp:
      server:
        stdio: true
        name: rdf-sparql
        version: ${build.version:0.0.0-SNAPSHOT}
        type: SYNC
  main:
    banner-mode: off
