name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Cache Maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ runner.arch }}-m2-${{ hashFiles('**/pom.xml', '.mvn/**') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-m2-

      - name: Run tests
        run: mise run build test

      - name: Run native tests
        run: mise run build --profile nativeTest test
