name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
concurrency:
  group: ci
  cancel-in-progress: false
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          mise version
          mise run build test
      - name: Run native tests
        run: mise run build --profile nativeTest test
