name: Assemble
on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
jobs:
  assemble:
    name: Assemble ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x86_64
            native_image_name: sparql-mcp-linux-x86_64
          - os: ubuntu-24.04-arm
            platform: linux-aarch_64
            native_image_name: sparql-mcp-linux-aarch_64
          - os: macos-latest
            platform: osx-aarch_64
            native_image_name: sparql-mcp-osx-aarch_64
          - os: windows-latest
            platform: windows-x86_64
            native_image_name: sparql-mcp-windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cache: true
      - name: Cache Maven
        id: cache-m2
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
            ~/.m2/mvnd
          key: ${{ runner.os }}-${{ runner.arch }}-m2-${{ hashFiles('**/pom.xml', '.mvn/**') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-m2-
      - name: Build
        run: mise run build --clean --profile native --native-image-name "${{ matrix.native_image_name }}" native:compile
      - name: Prepare archive input
        shell: bash
        run: |
          src="target/${{ matrix.native_image_name }}"
          dest="target/release/sparql-mcp"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            src="${src}.exe"
            dest="${dest}.exe"
          fi

          mkdir -p target/release
          cp "$src" "$dest"
      - name: Assemble native archive
        uses: jreleaser/release-action@v2
        with:
          setup-java: false
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}
      - name: Upload native artifact
        uses: actions/upload-artifact@v7
        with:
          retention-days: 1
          name: artifact-${{ matrix.platform }}
          path: out/jreleaser/assemble/sparqlMcp/archive/*.zip
          if-no-files-found: error
